### ISSUE TITLE
Dicom-Numpy should automatically renormalize pixel intensity based on RescaleSlope

### ISSUE THREAD

**Issue by dancingdarwin** [innolitics/dicom-numpy#1]
Hi there,
For PET images, it's typical for slices within the same time point to have different values for RescaleSlope and RescaleIntercept because of large differences of uptake from slice to slice. So it might make sense to just rescale the pixel data based on these values and then incorporate everything into the same 3D matrix rather than just giving an exception. This should be reasonably straight forward so if you don't have time I can just fork and file a pull request?

Thanks!

**Comment by johndgiese** [comment]
Hey @dancingdarwin it turns out we have already fixed this on master, it just isn't pushed.  I will try to push this sometime soon and will let you know when we do.

https://github.com/innolitics/dicom-numpy/blob/master/dicom_numpy/combine_slices.py#L80

**Comment by dancingdarwin** [comment]
OK thanks! Looking forward to seeing the push.

**Comment by johndgiese** [comment]
@dancingdarwin I just pushed version 0.1.2 of the software.  It should fix this issue.  Please confirm that it does when you have a chance!
