### ISSUE TITLE
The items in __all__ should be str and not function/class

### ISSUE THREAD

**Issue by jond01** [innolitics/dicom-numpy#12]
```python
from dicom_numpy import *
```
Produces the following error:
`TypeError: Item in dicom_numpy.__all__ must be str, not function`

**Comment by johndgiese** [comment]
FYI @jond01 I just pushed v0.4.0:

https://pypi.org/project/dicom-numpy/#history

See:

https://dicom-numpy.readthedocs.io/en/latest/#other-contributors

**Comment by jond01** [comment]
Oh very nice, congratulations on the new version and thanks @johndgiese! It will be very useful
