### ISSUE TITLE
Pixel Spacing

### ISSUE THREAD

**Issue by yee-ran** [innolitics/dicom-numpy#35]
Hi, after combining slices, how could I check the voxel spacing between each slice? Is that same as the pixel spacing in the 2D slice? Thanks!

**Comment by johndgiese** [comment]
It's not the same as the pixel spacing. You need to use the affine matrix that's returned to determine the spacing. Please see https://github.com/innolitics/dicom-numpy/blob/master/dicom_numpy/combine_slices.py#L180

**Comment by yee-ran** [comment]
@johndgiese Thank you so much! Is that normal that I got the array with elements -1000 as follows?

 [[-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  ...
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]]

**Comment by johndgiese** [comment]
That wouldn't surprise me to see large negative values on the edges of the image. It would surprise me if ALL the pixels are -1000.
