### ISSUE TITLE
COMBINE_SLICES doesn't work with Enhanced MR Image DICOM

### ISSUE THREAD

**Issue by JSousa-UoL** [innolitics/dicom-numpy#6]
Hi,

combine_slices() works very well for me for multiple 2D DICOM images, which is great.

However, it's not working correctly for Enhanced MR Images, which have a hierarchical structure. If I call subcategories in DICOM, it won't find most variables. The same happens if I call the function for the whole DICOM file (which is inside a list).

AttributeError: 'FileDataset' object has no attribute 'ImageOrientationPatient'

Other times when I run the same function, it complains about the SliceLocation.

I'm aware that this involves plenty of work, so I would like to suggest the Enhanced MR as improvement.

Kind regards,

João Sousa

**Comment by jond01** [comment]
Hi Joao,
Can you please share a sample of the data? I think it can be solved.

**Comment by JSousa-UoL** [comment]
Hi jonnd01,
Unfortunately I cannot share any of the data that I'm using, but you have some examples of Enhanced (some people know it by Multiframe) DICOM format.
The best examples I can give you now can be found under Sample Datasets in https://github.com/QIICR/ProjectIssuesAndWiki/wiki/DICOM-Enhanced-Multi-frame-for-data-exchange
Hope this helps!

**Comment by jond01** [comment]
Ok, it is indeed what I thought - a multi-frame dicom.
I downloaded the following MR dataset:
[ftp://medical.nema.org/MEDICAL/Dicom/Multiframe/MR/nemamfmr.imagesAB.tar.bz2]()

The following code block allows shorter access to some properties of a multi-frame dicom:
```python
from pydicom.dataset import FileDataset


def convert_ds(dataset):
    """
    Convert a dicom file with shared functional groups sequence into a class which enables shorter access to its
    properties. This is intended primarily for a single dicom file which includes several frames/slices.
    Usage example:
    >>> import pydicom
    >>> ds = pydicom.dcmread('single_dicom_file/I0')
    >>> ds = convert_ds(ds)
    >>> print(ds.PixelSpacing)
    """
    if hasattr(dataset, 'SharedFunctionalGroupsSequence') and len(dataset.SharedFunctionalGroupsSequence) > 0:
        dataset.__class__ = MultiFrameFileDataset
    return dataset


class MultiFrameFileDataset(FileDataset):
    """This class enables shorter access to basic properties of pydicom dataset of a certain type"""
    @property
    def ImageOrientationPatient(self):
        return self.SharedFunctionalGroupsSequence[0].PlaneOrientationSequence[0].ImageOrientationPatient

    @property
    def PixelSpacing(self):
        return self.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].PixelSpacing

    @property
    def SliceThickness(self):
        try:
            return self.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].SliceThickness
        except AttributeError:
            return self.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].SpacingBetweenSlices

    @property
    def RescaleIntercept(self):
        return self.SharedFunctionalGroupsSequence[0].PixelValueTransformationSequence[0].RescaleIntercept

    @property
    def RescaleSlope(self):
        return self.SharedFunctionalGroupsSequence[0].PixelValueTransformationSequence[0].RescaleSlope

    @property
    def ImagePositionPatient(self):
        """Note: this property returns only the position of the first slice"""
        return self.PerFrameFunctionalGroupsSequence[0].PlanePositionSequence[0].ImagePositionPatient

    def slice_positions(self):
        """Return a list of the slices' position"""
        return [seq.PlanePositionSequence[0].ImagePositionPatient for seq in self.PerFrameFunctionalGroupsSequence]

    def del_intensity_trans(self):
        """Delete the pixel value transformation sequence from dataset"""
        del self.SharedFunctionalGroupsSequence[0].PixelValueTransformationSequence

```

Testing this code on the sample datasets:
```python
from pathlib import Path

import pydicom
from dicom_numpy.combine_slices import _ijk_to_patient_xyz_transform_matrix


success = 0
total = 0
for file in Path('DISCIMG/IMAGES').glob('*'):
    try:
        ds = convert_ds(pydicom.dcmread(str(file)))
        transform = _ijk_to_patient_xyz_transform_matrix([ds])
        success += 1
    except AttributeError as e:
        print(f'Did not succeed on: {file.name}')
        print(e)
    finally:
        total += 1

print(f'{success} / {total}')
```

It works on 23/28. The 5 errors are for missing 'PlanePositionSequence' or 'PlaneOrientationSequence'.
It may require a bit more work, but you can get with it the affine matrix ("transform" in the code).
In order to make `combine_slices` work on a single dataset, there is another issue - #11.

I may create a pull request in the coming weeks to fix these issues.

**Comment by jond01** [comment]
Hi @JSousa-UoL, did the above work for your data?

**Comment by JSousa-UoL** [comment]
Hi @jond01, I'm really sorry I missed this and stopped coming here for quite a while.
I managed to find some time today and tested the code above in my data. It worked perfectly well, I liked the approach of shortening the length of the properties names. Thank you for doing this!

**Comment by jond01** [comment]
Glad to hear that @JSousa-UoL!

I think that you may find interest in the [*medio*](https://github.com/RSIP-Vision/medio) python package (can be installed with `pip install medio`).

You can probably replicate the above with:
```python
array, metadata = medio.read_img(filename)
```
Or:
```python
array, metadata = medio.read_img(filename, backend='pydicom')
```


I guess we can close this issue, as *dicom-numpy* was not designed in the first place to handle a multiframe dicom but dicom series.

**Comment by JSousa-UoL** [comment]
This is amazing, thank you so much for letting me know about this package! I've been looking for something that unifies pydicom, nibabel and itk in a flexible way.
You can close this issue.
Thank you once again @jond01

**Comment by jond01** [comment]
You are welcome @JSousa-UoL 🙂
(BTW, I cannot close the issue, but there should be some "Close issue" button next to the comment button.)
