### ISSUE TITLE
Reverse order of slices

### ISSUE THREAD

**Issue by lukaszmoroz** [innolitics/dicom-numpy#9]
https://github.com/innolitics/dicom-numpy/commit/abad26d82061a8c6b5eeba9353640292a1db3ac6
The changes introduced in this commit were justified by the fact that in DICOM, the first slice is considered the top of the patient, whereas the reverse is true: the Z axis increases from the feet towards the head, see e.g. https://dicom.innolitics.com/ciods/ct-image/image-plane/00200032
I'm trying to combine DICOM slices and convert the resulting stack into a NiFTI file, but when I render it in 3D Slicer, the volume is flipped along the Z axis.

**Comment by johndgiese** [comment]
Thanks for reporting this @lukaszmoroz , I think @ReeceStevens will be looking into this sometime soon.

**Comment by ReeceStevens** [comment]
Hi @lukaszmoroz , thanks for reporting this issue. The DICOM standard is quite clear that your point is correct:

> The z-axis is increasing toward the head of the patient.

I have reverted this commit and will push the fix out with release 0.3.0 of `dicom-numpy`, which will be coming very soon. I will close out this issue once the release has been published.

**Comment by ReeceStevens** [comment]
@lukaszmoroz Just as a heads up, the slice ordering issue has been resolved and 0.3.0 is now available on PyPI. Thanks again for reporting the issue!
